export interface Answer {
  uid: number
  studentName: string
  period: number
}

// 一期工程答案（UID 1-60）
const period1Answers: Answer[] = [
  { uid: 1, studentName: "李云翔", period: 1 },
  { uid: 2, studentName: "隗立聪", period: 1 },
  { uid: 3, studentName: "冯家铭", period: 1 },
  { uid: 4, studentName: "樊昊坤", period: 1 },
  { uid: 5, studentName: "张浩东", period: 1 },
  { uid: 6, studentName: "隗立聪", period: 1 },
  { uid: 7, studentName: "黄其琛", period: 1 },
  { uid: 8, studentName: "秦天瑞", period: 1 },
  { uid: 9, studentName: "冯家铭", period: 1 },
  { uid: 10, studentName: "黄其琛", period: 1 },
  { uid: 11, studentName: "冯家铭", period: 1 },
  { uid: 12, studentName: "王厚霖", period: 1 },
  { uid: 13, studentName: "张桁菘", period: 1 },
  { uid: 14, studentName: "张浩东", period: 1 },
  { uid: 15, studentName: "李云翔", period: 1 },
  { uid: 16, studentName: "李彦男", period: 1 },
  { uid: 17, studentName: "陈毓霖", period: 1 },
  { uid: 18, studentName: "李昊宸", period: 1 },
  { uid: 19, studentName: "李昊宸", period: 1 },
  { uid: 20, studentName: "黄其琛", period: 1 },
  { uid: 21, studentName: "隗立聪", period: 1 },
  { uid: 22, studentName: "陈毓霖", period: 1 },
  { uid: 23, studentName: "隗立聪", period: 1 },
  { uid: 24, studentName: "汪雨飞", period: 1 },
  { uid: 25, studentName: "李昊宸", period: 1 },
  { uid: 26, studentName: "康悦然", period: 1 },
  { uid: 27, studentName: "黄其琛", period: 1 },
  { uid: 28, studentName: "张桁菘", period: 1 },
  { uid: 29, studentName: "李彦男", period: 1 },
  { uid: 30, studentName: "李彦男", period: 1 },
  { uid: 31, studentName: "黄其琛", period: 1 },
  { uid: 32, studentName: "王厚霖", period: 1 },
  { uid: 33, studentName: "张桁菘", period: 1 },
  { uid: 34, studentName: "陈毓霖", period: 1 },
  { uid: 35, studentName: "李昊宸", period: 1 },
  { uid: 36, studentName: "康悦然", period: 1 },
  { uid: 37, studentName: "张浩东", period: 1 },
  { uid: 38, studentName: "秦天瑞", period: 1 },
  { uid: 39, studentName: "秦天瑞", period: 1 },
  { uid: 40, studentName: "陈毓霖", period: 1 },
  { uid: 41, studentName: "顾函瑜", period: 1 },
  { uid: 42, studentName: "黄其琛", period: 1 },
  { uid: 43, studentName: "李云翔", period: 1 },
  { uid: 44, studentName: "周瑞萌", period: 1 },
  { uid: 45, studentName: "张浩东", period: 1 },
  { uid: 46, studentName: "秦天瑞", period: 1 },
  { uid: 47, studentName: "孙宜林", period: 1 },
  { uid: 48, studentName: "江知白", period: 1 },
  { uid: 49, studentName: "黄其琛", period: 1 },
  { uid: 50, studentName: "康悦然", period: 1 },
  { uid: 51, studentName: "李姝文", period: 1 },
  { uid: 52, studentName: "李云翔", period: 1 },
  { uid: 53, studentName: "李昊宸", period: 1 },
  { uid: 54, studentName: "张浩东", period: 1 },
  { uid: 55, studentName: "熊瑽奕", period: 1 },
  { uid: 56, studentName: "江知白", period: 1 },
  { uid: 57, studentName: "隗立聪", period: 1 },
  { uid: 58, studentName: "秦天瑞", period: 1 },
  { uid: 59, studentName: "江知白", period: 1 },
  { uid: 60, studentName: "刘梓含", period: 1 },
]

// 二期工程答案（UID 61-100）
const period2Answers: Answer[] = [
  { uid: 61, studentName: "王厚霖", period: 2 },
  { uid: 62, studentName: "李昊宸", period: 2 },
  { uid: 63, studentName: "朱紫晗", period: 2 },
  { uid: 64, studentName: "康悦然", period: 2 },
  { uid: 65, studentName: "张桁菘", period: 2 },
  { uid: 66, studentName: "奚润皓", period: 2 },
  { uid: 67, studentName: "秦天瑞", period: 2 },
  { uid: 68, studentName: "李昊宸", period: 2 },
  { uid: 69, studentName: "尹一博", period: 2 },
  { uid: 70, studentName: "樊昊坤", period: 2 },
  { uid: 71, studentName: "张赫", period: 2 },
  { uid: 72, studentName: "江知白", period: 2 },
  { uid: 73, studentName: "李云翔", period: 2 },
  { uid: 74, studentName: "黄其琛", period: 2 },
  { uid: 75, studentName: "胡鑫鹏", period: 2 },
  { uid: 76, studentName: "张桁菘", period: 2 },
  { uid: 77, studentName: "李姝文", period: 2 },
  { uid: 78, studentName: "李昊宸", period: 2 },
  { uid: 79, studentName: "赵梓烨", period: 2 },
  { uid: 80, studentName: "尹一博", period: 2 },
  { uid: 81, studentName: "汪雨飞", period: 2 },
  { uid: 82, studentName: "江知白", period: 2 },
  { uid: 83, studentName: "奚润皓", period: 2 },
  { uid: 84, studentName: "李雨锌", period: 2 },
  { uid: 85, studentName: "陈美卿", period: 2 },
  { uid: 86, studentName: "江知白", period: 2 },
  { uid: 87, studentName: "李雨锌", period: 2 },
  { uid: 88, studentName: "秦天瑞", period: 2 },
  { uid: 89, studentName: "赵梓烨", period: 2 },
  { uid: 90, studentName: "奚润皓", period: 2 },
  { uid: 91, studentName: "王梦源", period: 2 },
  { uid: 92, studentName: "顾函瑜", period: 2 },
  { uid: 93, studentName: "陈美卿", period: 2 },
  { uid: 94, studentName: "秦天瑞", period: 2 },
  { uid: 95, studentName: "李昊宸", period: 2 },
  { uid: 96, studentName: "李彦男", period: 2 },
  { uid: 97, studentName: "陈毓霖", period: 2 },
  { uid: 98, studentName: "张赫", period: 2 },
  { uid: 99, studentName: "隗立聪", period: 2 },
  { uid: 100, studentName: "李昊宸", period: 2 },
]

// 合并所有答案
export const answers: Answer[] = [...period1Answers, ...period2Answers]

// 根据UID获取答案
export function getAnswerByUid(uid: number): Answer | undefined {
  return answers.find((answer) => answer.uid === uid)
}
